name: PublishTypescriptClientToNPM

on:
  pull_request:
  push:
    tags:
      - v*.*.*

jobs:
  generateTypescriptBinding:
    name: Generate Typescript Binding
    uses: luiz-couto/open-api-workflows-tests/.github/workflows/gen-binding.yml@feature/open-api-workflows
    secrets: inherit
  publishToNpm:
    name: Publish Typescript Binding to NPM
    needs: generateTypescriptBinding
    runs-on: ubuntu-latest
    steps:
      - name: Download Typescript Binding from previous job
        uses: actions/download-artifact@v3
        with:
          name: typescript-binding

      - name: Initialize NPM Package
        run: > 
          npm init -y &&
          npm pkg set
          name=workflow-tests
          version=1.2.0
          author=luizcouto
          description='Typescript binding for workflow tests'
          main='dist/index.js'
          types='dist/index.d.ts'

      # # Missiing configs
      # - name: Config Typescript
      #   run: tsc --init

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: '16.x'
      #     registry-url: 'https://registry.npmjs.org'
      # - run: npm ci
      # - run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      

      

      

      
